services:
  dns-service-ptech:
    image: ptech_duck_dns:latest
    ports:
      - "4443:443" # Mapea el puerto del contenedor al host
      - "8080:443"
    environment:
      RUST_LOG: "info" # Define variables de entorno si tu aplicación las usa
    restart: always # Reinicia el contenedor si falla